import Link from "next/link";
import Script from "next/script";

export const metadata = { title: "Section 80C and Tax-Saving Investments: Check Eligibility First", description: "Understand how to review tax-saving investments, deduction eligibility and regime rules for the relevant Indian tax year.", alternates: { canonical: "/learn/tax/80c-beyond-the-obvious" } };
const COLOR = "#16a34a";

export default function Section80cGuidePage() {
  const faq = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
    { "@type": "Question", name: "Does every taxpayer get a deduction for 80C investments?", acceptedAnswer: { "@type": "Answer", text: "No. Eligibility depends on the applicable law, tax regime, taxpayer and nature of the payment or investment. Check current official guidance and your specific return instructions." } },
    { "@type": "Question", name: "Is NPS always an extra deduction?", acceptedAnswer: { "@type": "Answer", text: "NPS tax treatment depends on the contribution type, taxpayer, employer arrangement, applicable regime and year. Check the current rules; do not assume that every contribution qualifies for an additional deduction." } },
    { "@type": "Question", name: "Should I invest in ELSS only for tax savings?", acceptedAnswer: { "@type": "Answer", text: "No. ELSS is a market-linked mutual fund and can lose value. Assess its risk, investment horizon, lock-in, costs and suitability, along with whether a deduction is actually available to you." } },
  ] };
  const article = { "@context": "https://schema.org", "@type": "Article", headline: "Section 80C and Tax-Saving Investments: Check Eligibility First", author: { "@type": "Person", name: "Ash K" }, datePublished: "2026-06-04", dateModified: "2026-09-28", publisher: { "@type": "Organization", name: "Assure Fintech" } };
  return <>
    <div style={{ background: "linear-gradient(135deg, #052E16, #166534, #052E16)", padding: "48px 24px", marginTop: 64 }}><div style={{ maxWidth: 820, margin: "0 auto" }}><div style={{ color: "#bbf7d0", fontSize: 13, marginBottom: 12 }}>Tax planning · Deductions</div><h1 style={{ color: "#F1F5F9", fontSize: "clamp(28px, 4vw, 40px)", lineHeight: 1.15, margin: "0 0 12px" }}>Tax-saving investments: verify the deduction before investing</h1><p style={{ color: "#dcfce7", margin: 0, lineHeight: 1.6 }}>An investment’s tax treatment depends on the applicable tax year, regime and eligibility—not only its product label.</p></div></div>
    <main style={{ maxWidth: 820, margin: "0 auto", padding: "30px 22px 56px", color: "var(--text)", lineHeight: 1.7 }}>
      <Script id="ld-art" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(article) }} /><Script id="ld-faq" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faq) }} />
      <nav aria-label="Breadcrumb" style={{ fontSize: 13, color: "var(--text-muted)", marginBottom: 22 }}><Link href="/" style={{ color: "inherit" }}>Home</Link> / <Link href="/learn/tax" style={{ color: "inherit" }}>Tax</Link> / Tax-saving investments</nav>
      <section><h2 style={{ color: COLOR }}>First identify the law and regime</h2><p>For income earned from 1 April 2025 to 31 March 2026, a return filed for AY 2026–27 remains under the Income-tax Act, 1961; the deduction is still commonly called section 80C. For income earned from 1 April 2026 onward, the Income-tax Act, 2025 uses Tax Year 2026–27 and reorganizes the corresponding eligible-payment deduction under section 123 and Schedule XV. In that new Act, section 123 is not available if you choose the default concessional regime under section 202. Use the correct official calculator and the rules for the exact period.</p></section>
      <section aria-labelledby="deduction-example" style={{ marginTop: 22, padding: 20, borderRadius: 14, background: "var(--bg-muted)", border: "1px solid var(--border)" }}><h2 id="deduction-example" style={{ color: COLOR, marginTop: 0 }}>Worked example: the combined limit is not per product</h2><p>For an individual eligible to use the old regime for AY 2026–27, suppose the year’s eligible EPF contribution is ₹70,000, qualifying life-insurance premium is ₹35,000, and qualifying tuition fees are ₹55,000. The total is ₹1,60,000, but the combined section 80C/80CCC/80CCD(1) limit is ₹1,50,000. The excess ₹10,000 does not create another deduction under this combined limit.</p><p>That is a limit illustration, not a conclusion that every payment qualifies. Check who paid, who is covered, policy or investment conditions, payment timing and the regime. For Tax Year 2026–27, the corresponding section 123/Schedule XV deduction also has a ₹1,50,000 cap, but is unavailable in the section 202 new regime.</p></section>
      <section><h2 style={{ color: COLOR }}>Separate tax treatment from product suitability</h2><p>Tax-saving products can differ substantially in risk, liquidity, lock-in, fees and returns. A market-linked fund is not equivalent to a deposit or a government-backed scheme. Compare each product’s official documents and consider your investment goal and ability to bear losses. A deduction, if available, does not guarantee that an investment is appropriate or profitable.</p><p>NPS, provident-fund contributions, insurance premiums, tuition-related payments and other eligible items may have different conditions. Do not double-count amounts or treat an employer contribution the same as your own payment. If unsure, ask a tax professional before making an irreversible investment or filing a claim.</p></section>
      <section><h2 style={{ color: COLOR }}>Frequently asked questions</h2>{faq.mainEntity.map((item) => <details key={item.name} style={{ borderBottom: "1px solid var(--border)", padding: "14px 0" }}><summary style={{ cursor: "pointer", fontWeight: 650 }}>{item.name}</summary><p style={{ color: "var(--text-muted)" }}>{item.acceptedAnswer.text}</p></details>)}</section>
      <p style={{ marginTop: 24 }}><a href="https://www.incometax.gov.in/iec/foportal/help/individual/return-applicable-1" target="_blank" rel="noopener noreferrer" style={{ color: COLOR }}>Income Tax Department: AY 2026–27 deductions and regime rules</a> · <a href="https://www.incometaxindia.gov.in/w/section-123-92" target="_blank" rel="noopener noreferrer" style={{ color: COLOR }}>section 123 of the Income-tax Act, 2025</a> · <a href="https://www.incometax.gov.in/iec/foportal/help/all-topics/e-filing-services/set-offcarry-forward-losses" target="_blank" rel="noopener noreferrer" style={{ color: COLOR }}>official section 123 and new-regime FAQ</a> · <Link href="/learn/tax" style={{ color: COLOR }}>Tax guides</Link></p>
      <p style={{ borderTop: "1px solid var(--border)", paddingTop: 16, fontSize: 13, color: "var(--text-muted)" }}>General educational information, not tax, investment or legal advice. Verify current rules and eligibility with official sources or a qualified adviser.</p>
    </main>
  </>;
}
