import Link from "next/link";
import Script from "next/script";

export const metadata = { title: "Section 80C and Tax-Saving Investments: Check Eligibility First", description: "Understand how to review tax-saving investments, deduction eligibility and regime rules for the relevant Indian tax year.", alternates: { canonical: "/learn/tax/80c-beyond-the-obvious" } };
const COLOR = "#16a34a";

export default function Section80cGuidePage() {
  const faq = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
    { "@type": "Question", name: "Does every taxpayer get a deduction for 80C investments?", acceptedAnswer: { "@type": "Answer", text: "No. Eligibility depends on the applicable law, tax regime, taxpayer and nature of the payment or investment. Check current official guidance and your specific return instructions." } },
    { "@type": "Question", name: "Is NPS always an extra deduction?", acceptedAnswer: { "@type": "Answer", text: "NPS tax treatment depends on the contribution type, taxpayer, employer arrangement, applicable regime and year. Check the current rules; do not assume that every contribution qualifies for an additional deduction." } },
    { "@type": "Question", name: "Should I invest in ELSS only for tax savings?", acceptedAnswer: { "@type": "Answer", text: "No. ELSS is a market-linked mutual fund and can lose value. Assess its risk, investment horizon, lock-in, costs and suitability, along with whether a deduction is actually available to you." } },
  ] };
  const article = { "@context": "https://schema.org", "@type": "Article", headline: "Section 80C and Tax-Saving Investments: Check Eligibility First", author: { "@type": "Person", name: "Ash K" }, datePublished: "2026-06-04", dateModified: "2026-09-25", publisher: { "@type": "Organization", name: "Assure Fintech" } };
  return <>
    <div style={{ background: "linear-gradient(135deg, #052E16, #166534, #052E16)", padding: "48px 24px", marginTop: 64 }}><div style={{ maxWidth: 820, margin: "0 auto" }}><div style={{ color: "#bbf7d0", fontSize: 13, marginBottom: 12 }}>Tax planning · Deductions</div><h1 style={{ color: "#F1F5F9", fontSize: "clamp(28px, 4vw, 40px)", lineHeight: 1.15, margin: "0 0 12px" }}>Tax-saving investments: verify the deduction before investing</h1><p style={{ color: "#dcfce7", margin: 0, lineHeight: 1.6 }}>An investment’s tax treatment depends on the applicable tax year, regime and eligibility—not only its product label.</p></div></div>
    <main style={{ maxWidth: 820, margin: "0 auto", padding: "30px 22px 56px", color: "var(--text)", lineHeight: 1.7 }}>
      <Script id="ld-art" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(article) }} /><Script id="ld-faq" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faq) }} />
      <nav aria-label="Breadcrumb" style={{ fontSize: 13, color: "var(--text-muted)", marginBottom: 22 }}><Link href="/" style={{ color: "inherit" }}>Home</Link> / <Link href="/learn/tax" style={{ color: "inherit" }}>Tax</Link> / Tax-saving investments</nav>
      <section><h2 style={{ color: COLOR }}>Check four things before relying on a deduction</h2><ol><li>Which assessment year or tax year applies to the income and payment?</li><li>Which tax regime are you using, and is the deduction permitted under it?</li><li>Does the payment, account or investment meet the relevant statutory conditions and limits?</li><li>What records, dates or forms must you retain or report?</li></ol><p>Do not infer current eligibility from a previous year’s summary. Where rules are transitioning, use the Income Tax Department’s current return instructions and guidance for the exact year.</p></section>
      <section><h2 style={{ color: COLOR }}>Separate tax treatment from product suitability</h2><p>Tax-saving products can differ substantially in risk, liquidity, lock-in, fees and returns. A market-linked fund is not equivalent to a deposit or a government-backed scheme. Compare each product’s official documents and consider your investment goal and ability to bear losses. A deduction, if available, does not guarantee that an investment is appropriate or profitable.</p><p>NPS, provident-fund contributions, insurance premiums, tuition-related payments and other eligible items may have different conditions. Do not double-count amounts or treat an employer contribution the same as your own payment. If unsure, ask a tax professional before making an irreversible investment or filing a claim.</p></section>
      <section><h2 style={{ color: COLOR }}>Frequently asked questions</h2>{faq.mainEntity.map((item) => <details key={item.name} style={{ borderBottom: "1px solid var(--border)", padding: "14px 0" }}><summary style={{ cursor: "pointer", fontWeight: 650 }}>{item.name}</summary><p style={{ color: "var(--text-muted)" }}>{item.acceptedAnswer.text}</p></details>)}</section>
      <p style={{ marginTop: 24 }}><a href="https://www.incometax.gov.in/iec/foportal/help/individual/return-applicable-1" target="_blank" rel="noopener noreferrer" style={{ color: COLOR }}>Income Tax Department: individual return guidance</a> · <Link href="/learn/tax" style={{ color: COLOR }}>Tax guides</Link></p>
      <p style={{ borderTop: "1px solid var(--border)", paddingTop: 16, fontSize: 13, color: "var(--text-muted)" }}>General educational information, not tax, investment or legal advice. Verify current rules and eligibility with official sources or a qualified adviser.</p>
    </main>
  </>;
}
