/** @type {import('next').NextConfig} */
const legacyRedirects = [
  ['/cards/amazon-pay-icici', '/cards/amazon-icici'],
  ['/cards/idfc-first-wow', '/cards/idfc-wow'],
  ['/cards/scapia-federal', '/cards/scapia'],
  ['/cards/sbi-card-elite', '/cards/sbi-elite'],
  ['/author/ash-k', '/about'],
  ['/best', '/cards'],
  ['/learn', '/blog'],
  ['/learn/credit-cards', '/blog'],
  ['/tools/emi-calculator', '/loan-calculator'],
  ['/tools/income-tax-calculator', '/tax-calculator'],
  ['/tools/sip-calculator', '/sip-calculator'],
  ['/tools/cashback-calculator', '/smart-swipe'],
  ['/best/credit-card-online-shopping', '/best/credit-card-for-online-shopping'],
  ['/best/credit-card-with-no-forex-markup', '/best/best-credit-card-with-no-forex-markup'],
  ['/best/credit-card-for-beginners-india', '/best/best-credit-card-for-beginners-india'],
  ['/best/credit-card-for-bill-payments', '/best/best-credit-card-for-bill-payments'],
  ['/best/credit-card-for-emi-purchases', '/best/best-credit-card-for-emi-purchases'],
  ['/best/credit-card-for-health-insurance-payment', '/best/best-credit-card-for-health-insurance-payment'],
  ['/best/credit-card-for-high-income-earners', '/best/best-credit-card-for-high-income-earners'],
  ['/best/credit-card-for-lounge-access', '/best/best-credit-card-for-lounge-access'],
  ['/best/credit-card-for-rent-payment', '/best/best-credit-card-for-rent-payment'],
  ['/best/credit-card-for-students-india', '/best/best-credit-card-for-students-india'],
  ['/best/credit-card-for-upi-payments', '/best/best-credit-card-for-upi-payments'],
  ['/best/credit-card-for-women-india', '/best/best-credit-card-for-women-india'],
  ['/blog/credit-utilisation-ratio-guide', '/blog/credit-utilization-ratio-guide'],
  ['/compare/direct-vs-regular', '/learn/mutual-funds/direct-vs-regular'],
  ['/compare/hdfc-click2protect-vs-icici-iprotect', '/compare/compare-hdfc-click2protect-vs-icici-iprotect'],
  ['/compare/hdfc-optima-secure-vs-niva-bupa-reassure', '/compare/compare-hdfc-optima-secure-vs-niva-bupa-reassure'],
  ['/compare/hdfc-regalia-vs-axis-magnus', '/compare/compare-hdfc-regalia-vs-axis-magnus'],
  ['/calculators', '/smart-swipe'],
  ['/blog/miles-vs-cashback-india-2026', '/blog/reward-points-vs-cashback'],
  ['/blog/axis-atlas-edge-miles-partners-2026', '/cards/axis-atlas'],
  ['/blog/axis-atlas-vs-magnus-2026', '/compare'],
  ['/blog/scapia-federal-card-review-2026', '/cards/scapia'],
  ['/blog/credit-card-insurance-premium-exclusions-india', '/best/best-credit-card-for-insurance-premium'],
  ['/blog/how-to-choose-first-credit-card-2026', '/blog/first-card-decision-framework'],
  ['/learn/credit-cards/cibil-score-explained', '/blog/cibil-score-101-india'],
  ['/best/credit-card-students', '/best/best-credit-card-for-students-india'],
  ['/best/credit-card-first-salary', '/best/best-credit-card-for-beginners-india'],
  ['/best/credit-card-self-employed', '/blog/best-card-freelancers-2026'],
  ['/learn/tax/section-80c', '/learn/tax/80c-beyond-the-obvious'],
  ['/best/credit-card-food-delivery', '/best/credit-card-for-swiggy-zomato'],
  ['/best/credit-card-fuel', '/best/credit-card-for-fuel'],
  ['/blog/cashback-vs-reward-points', '/blog/reward-points-vs-cashback'],
  ['/blog/premium-card-review-framework', '/blog/annual-fee-when-worth-paying'],
  ['/learn/credit-cards/apr-vs-interest', '/learn/loans/personal-loan-actual-apr'],
  ['/learn/credit-cards/minimum-due-trap', '/blog/right-way-pay-credit-card-bill'],
  ['/learn/credit-cards/forex-markup', '/best/best-credit-card-with-no-forex-markup'],
  ['/best/balance-transfer-credit-card', '/cards'],
  ['/learn/loans/home-loan-eligibility', '/learn/loans/home-loan-true-cost'],
  ['/learn/loans/prepayment-strategy', '/learn/loans/prepayment-penalty-trap'],
  ['/learn/loans/balance-transfer', '/learn/loans'],
  ['/learn/tax/section-24b', '/learn/tax'],
  ['/learn/insurance/super-top-up', '/learn/insurance/health-insurance-effective-coverage'],
  ['/best/health-insurance-parents', '/learn/insurance/health-insurance-for-parents'],
  ['/blog/irdai-2025-cashless-network', '/learn/insurance'],
  ['/learn/savings/dicgc-explained', '/learn/savings'],
  ['/learn/savings/sweep-fd', '/learn/savings/fd-real-return'],
  ['/best/fd-senior-citizens', '/learn/savings/senior-citizen-fd'],
  ['/best/mutual-fund-emergency-fund', '/learn/mutual-funds'],
  ['/learn/tax/section-80d', '/learn/tax'],
  ['/learn/tax/hra-exemption', '/learn/tax/hra-calculation'],
  ['/cards/flipkart-axis-supercoin', '/cards/axis-flipkart-supercoin'],
  ['/cards/onecard-metal', '/cards/onecard'],
  ['/blog/credit-card-utility-rewards-history-india', '/best/best-credit-card-for-bill-payments'],
  ['/blog/bbps-credit-card-rewards-guide', '/best/best-credit-card-for-bill-payments'],
  ['/blog/international-spending-card-strategy-india', '/best/credit-card-for-international-spending'],
  ['/blog/forex-markup-india-guide', '/best/best-credit-card-with-no-forex-markup'],
  ['/blog/forex-markup-india-explained', '/best/best-credit-card-with-no-forex-markup'],
  ['/blog/axis-ace-review-2026', '/cards/axis-ace'],
  ['/blog/axis-ace-vs-amazon-pay-icici-2026', '/compare'],
  ['/blog/free-credit-card-stack-india-2026', '/stack-builder'],
  ['/cards/idfc-first-millennia', '/cards/idfc-millennia'],
  ['/blog/autopay-credit-card-setup-india', '/blog/right-way-pay-credit-card-bill'],
  ['/blog/cibil-score-credit-card-india', '/blog/cibil-score-101-india'],
  ['/blog/first-credit-card-india-2026', '/blog/first-card-decision-framework'],
  ['/cards/sbi-student-plus', '/best/best-credit-card-for-students-india'],
  ['/cards/icici-platinum-chip', '/cards/icici-platinum'],
  ['/cards/federal-bank-fd-credit-card', '/cards/idfc-wow'],
  ['/blog/fd-secured-credit-card-india-2026', '/best/best-credit-card-for-students-india'],
  ['/blog/cibil-score-from-zero-india', '/blog/cibil-score-101-india'],
  ['/cards/hdfc-millennia-rupay', '/cards/hdfc-millennia'],
  ['/cards/idfc-first-wow-rupay', '/cards/idfc-wow'],
  ['/cards/sbi-simplysave-rupay', '/cards/sbi-simplysave'],
  ['/blog/rupay-credit-card-upi-rewards-india-2026', '/best/best-credit-card-for-upi-payments'],
  ['/blog/zero-mdr-upi-credit-card-india', '/blog/upi-vs-credit-cards-india'],
  ['/blog/bookmyshow-credit-card-offers-2026', '/best/best-credit-card-for-movie-entertainment'],
  ['/blog/nobroker-rent-credit-card-fee-india', '/best/best-credit-card-for-rent-payment'],
  ['/blog/emi-reward-points-india', '/best/best-credit-card-for-emi-purchases'],
  ['/blog/priority-pass-india-guide', '/best/best-credit-card-for-lounge-access'],
  ['/cards/hdfc-regalia-gold', '/cards/hdfc-regalia'],
  ['/blog/women-credit-card-india-2026', '/best/best-credit-card-for-women-india'],
  ['/blog/invite-only-cards-india-guide', '/cards/hdfc-infinia'],
];

const nextConfig = {
  reactStrictMode: true,
  outputFileTracingRoot: __dirname,
  async redirects() {
    return [
      ...legacyRedirects.map(([source, destination]) => ({
        source,
        destination,
        permanent: true,
      })),
      {
        source: '/:path*',
        has: [{ type: 'host', value: 'assurefintech.com' }],
        destination: 'https://www.assurefintech.com/:path*',
        permanent: true,
      },
    ];
  },
};

module.exports = nextConfig;
