import Link from "next/link";
import Script from "next/script";

export const metadata = { title: "Tax on Credit-Card Rewards: Questions to Check", description: "Credit-card reward tax treatment can depend on the facts and how a benefit was earned. Learn what to document and when to seek tax advice.", alternates: { canonical: "/learn/tax/tax-on-credit-card-rewards" } };
const COLOR = "#16a34a";

export default function TaxOnCreditCardRewardsPage() {
  const faq = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
    { "@type": "Question", name: "Are personal credit-card reward points always tax-free?", acceptedAnswer: { "@type": "Answer", text: "Do not assume that every reward or redemption has the same tax treatment. The facts—including whether the benefit is a purchase-linked discount, prize, referral benefit, employer-provided perk or business-related reward—may matter. Check current official guidance or obtain individual tax advice." } },
    { "@type": "Question", name: "Are prizes from a card promotion treated like ordinary reward points?", acceptedAnswer: { "@type": "Answer", text: "A prize or promotional win may be treated differently from a benefit linked to ordinary purchases. Review the promotion terms and current tax and withholding rules, and retain any tax certificate or communication from the payer." } },
    { "@type": "Question", name: "What if I use a company card for business spending?", acceptedAnswer: { "@type": "Answer", text: "Follow the employer's expense and rewards policy. Ownership and personal use of benefits earned from business spending can raise employment and tax questions; ask your employer and a qualified tax professional rather than assuming the points are personal or tax-free." } },
  ] };
  const article = { "@context": "https://schema.org", "@type": "Article", headline: "Tax on Credit-Card Rewards: Questions to Check", author: { "@type": "Person", name: "Ash K" }, datePublished: "2026-06-04", dateModified: "2026-09-25", publisher: { "@type": "Organization", name: "Assure Fintech" } };
  return <>
    <div style={{ background: "linear-gradient(135deg, #052E16, #166534, #052E16)", padding: "48px 24px", marginTop: 64 }}><div style={{ maxWidth: 820, margin: "0 auto" }}><div style={{ color: "#bbf7d0", fontSize: 13, marginBottom: 12 }}>Tax planning · Card rewards</div><h1 style={{ color: "#F1F5F9", fontSize: "clamp(28px, 4vw, 40px)", lineHeight: 1.15, margin: "0 0 12px" }}>Credit-card rewards and tax: check how the benefit arose</h1><p style={{ color: "#dcfce7", margin: 0, lineHeight: 1.6 }}>There is no safe universal answer for every kind of points, cashback, promotion or business-card benefit.</p></div></div>
    <main style={{ maxWidth: 820, margin: "0 auto", padding: "30px 22px 56px", color: "var(--text)", lineHeight: 1.7 }}>
      <Script id="ld-art" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(article) }} /><Script id="ld-faq" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faq) }} />
      <nav aria-label="Breadcrumb" style={{ fontSize: 13, color: "var(--text-muted)", marginBottom: 22 }}><Link href="/" style={{ color: "inherit" }}>Home</Link> / <Link href="/learn/tax" style={{ color: "inherit" }}>Tax</Link> / Card rewards</nav>
      <section><h2 style={{ color: COLOR }}>First identify the type of benefit</h2><p>Rewards earned as part of a personal purchase, cash or points awarded for a promotion, referral benefits, and rewards attached to business expenditure are not necessarily the same tax question. The issuer’s label is useful evidence but does not, by itself, decide the tax treatment.</p><p>Check the card terms, promotion terms, statement, redemption record and any certificate or tax deduction information. Record whether the spending was personal, reimbursed or incurred for an employer or business, and who was entitled to use the resulting benefit.</p></section>
      <section><h2 style={{ color: COLOR }}>Questions to resolve for your situation</h2><ul><li>Was the benefit a reduction in the price of something you bought, a separate prize or payment, or compensation for a referral or activity?</li><li>Was it earned through personal spending or business/employer spending?</li><li>Was tax withheld, and is there a certificate or information in your tax records?</li><li>Which tax year and reporting rules apply, and does the benefit need to be reported under your circumstances?</li></ul><p>Where the amount is material, the treatment is unclear, or a business/employer is involved, ask a qualified tax professional. Do not rely on a general article or social-media interpretation as a filing position.</p></section>
      <section><h2 style={{ color: COLOR }}>Frequently asked questions</h2>{faq.mainEntity.map((item) => <details key={item.name} style={{ borderBottom: "1px solid var(--border)", padding: "14px 0" }}><summary style={{ cursor: "pointer", fontWeight: 650 }}>{item.name}</summary><p style={{ color: "var(--text-muted)" }}>{item.acceptedAnswer.text}</p></details>)}</section>
      <p style={{ marginTop: 24 }}><a href="https://www.incometax.gov.in/" target="_blank" rel="noopener noreferrer" style={{ color: COLOR }}>Income Tax Department of India</a> · <Link href="/learn/tax" style={{ color: COLOR }}>Tax guides</Link></p>
      <p style={{ borderTop: "1px solid var(--border)", paddingTop: 16, fontSize: 13, color: "var(--text-muted)" }}>General educational information, not tax or legal advice. Tax outcomes depend on current law and individual facts; seek qualified advice before filing where necessary.</p>
    </main>
  </>;
}
