import Link from "next/link";
import Script from "next/script";

export const metadata = { title: "HRA Exemption: Calculation and Eligibility Checklist", description: "Understand the HRA exemption calculation, evidence to retain and why regime and tax-year eligibility must be checked before filing.", alternates: { canonical: "/learn/tax/hra-calculation" } };
const COLOR = "#16a34a";

export default function HraCalculationPage() {
  const faq = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
    { "@type": "Question", name: "Can I claim HRA under the new tax regime?", acceptedAnswer: { "@type": "Answer", text: "The availability of HRA exemption depends on the applicable regime and tax-year rules. The Income Tax Department's current guidance for the return period says HRA exemption is available under the old regime and not the new regime; check the current rules for the year you are filing." } },
    { "@type": "Question", name: "How is HRA exemption generally calculated?", acceptedAnswer: { "@type": "Answer", text: "For eligible salaried taxpayers, the exemption is generally based on the least of actual HRA received, rent paid less 10% of the relevant salary, and the prescribed 40% or 50% salary limit depending on the applicable city classification. Verify the exact salary definition and rules for your year." } },
    { "@type": "Question", name: "What records should I keep for an HRA claim?", acceptedAnswer: { "@type": "Answer", text: "Keep salary records, rent receipts or other proof of rent, landlord details and any required payment evidence or declarations. Documentation requirements can depend on the amount and the return rules for the year." } },
  ] };
  const article = { "@context": "https://schema.org", "@type": "Article", headline: "HRA Exemption: Calculation and Eligibility Checklist", author: { "@type": "Person", name: "Ash K" }, datePublished: "2026-06-04", dateModified: "2026-09-25", publisher: { "@type": "Organization", name: "Assure Fintech" } };
  return <>
    <div style={{ background: "linear-gradient(135deg, #052E16, #166534, #052E16)", padding: "48px 24px", marginTop: 64 }}><div style={{ maxWidth: 820, margin: "0 auto" }}><div style={{ color: "#bbf7d0", fontSize: 13, marginBottom: 12 }}>Tax planning · Salary and rent</div><h1 style={{ color: "#F1F5F9", fontSize: "clamp(28px, 4vw, 40px)", lineHeight: 1.15, margin: "0 0 12px" }}>HRA exemption: calculation, eligibility and records</h1><p style={{ color: "#dcfce7", margin: 0, lineHeight: 1.6 }}>Use the applicable tax-year instructions and your payroll details; a calculator cannot establish eligibility by itself.</p></div></div>
    <main style={{ maxWidth: 820, margin: "0 auto", padding: "30px 22px 56px", color: "var(--text)", lineHeight: 1.7 }}>
      <Script id="ld-art" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(article) }} /><Script id="ld-faq" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faq) }} />
      <nav aria-label="Breadcrumb" style={{ fontSize: 13, color: "var(--text-muted)", marginBottom: 22 }}><Link href="/" style={{ color: "inherit" }}>Home</Link> / <Link href="/learn/tax" style={{ color: "inherit" }}>Tax</Link> / HRA</nav>
      <section><h2 style={{ color: COLOR }}>General calculation structure</h2><p>For an eligible salaried taxpayer, the HRA exemption is generally the lowest of: (1) HRA received from the employer; (2) rent paid less 10% of the relevant salary; and (3) the prescribed 40% or 50% salary limit, depending on the applicable city classification. The salary definition and exact conditions are set by the tax rules; check the current instructions before using the formula.</p><p>A simple illustration can help explain the minimum-of-three method, but it is not an assessment of your claim. Payroll components, periods of rent, changes of city or employer, unpaid rent, and other facts can change the calculation. Use the official return utility or qualified professional for the filing year.</p></section>
      <section><h2 style={{ color: COLOR }}>Eligibility and documents</h2><ul><li>Confirm HRA was received as part of eligible salary and that the chosen tax regime permits the claim.</li><li>Use rent actually paid for the relevant period; do not claim a notional amount.</li><li>Retain rent receipts or other evidence, rental agreement if applicable, salary statements, and payment records.</li><li>Provide any landlord or payment details required by the employer or return forms.</li><li>Check current rules if renting from a relative; the arrangement must be genuine and properly documented.</li></ul></section>
      <section><h2 style={{ color: COLOR }}>Frequently asked questions</h2>{faq.mainEntity.map((item) => <details key={item.name} style={{ borderBottom: "1px solid var(--border)", padding: "14px 0" }}><summary style={{ cursor: "pointer", fontWeight: 650 }}>{item.name}</summary><p style={{ color: "var(--text-muted)" }}>{item.acceptedAnswer.text}</p></details>)}</section>
      <p style={{ marginTop: 24 }}><a href="https://www.incometax.gov.in/iec/foportal/help/individual/return-applicable-1" target="_blank" rel="noopener noreferrer" style={{ color: COLOR }}>Income Tax Department: current salaried taxpayer return guidance</a> · <Link href="/learn/tax/old-vs-new-regime" style={{ color: COLOR }}>compare tax regimes</Link></p>
      <p style={{ borderTop: "1px solid var(--border)", paddingTop: 16, fontSize: 13, color: "var(--text-muted)" }}>General educational information, not tax or legal advice. Verify the correct tax year, eligibility and documentation requirements before filing.</p>
    </main>
  </>;
}
