import Link from "next/link";
import Script from "next/script";

export const metadata = { title: "Old vs New Tax Regime: Compare for Your Tax Year", description: "A framework for comparing the Indian tax regimes using your income, eligible claims and the rules for the relevant assessment or tax year.", alternates: { canonical: "/learn/tax/old-vs-new-regime" } };
const COLOR = "#16a34a";

export default function OldVsNewTaxRegimePage() {
  const faq = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
    { "@type": "Question", name: "Which tax regime is better?", acceptedAnswer: { "@type": "Answer", text: "There is no universal winner or deduction break-even amount. Compare your tax under the rules for the correct year, using eligible income, deductions, exemptions, rebates and special-rate income." } },
    { "@type": "Question", name: "Which year's tax rules should I use?", acceptedAnswer: { "@type": "Answer", text: "Identify the year the income was earned and the corresponding return or tax year. Transitional changes mean that assessment-year and tax-year terminology may differ; use current official guidance for your situation." } },
    { "@type": "Question", name: "Can I change regimes each year?", acceptedAnswer: { "@type": "Answer", text: "The available choice and timing depend on the taxpayer's income type and current law. Business or professional income can have additional election rules. Confirm eligibility and filing deadlines with the Income Tax Department or a qualified tax professional." } },
  ] };
  const article = { "@context": "https://schema.org", "@type": "Article", headline: "Old vs New Tax Regime: Compare for Your Tax Year", author: { "@type": "Person", name: "Ash K" }, datePublished: "2026-04-20", dateModified: "2026-09-26", publisher: { "@type": "Organization", name: "Assure Fintech" } };
  return <>
    <div style={{ background: "linear-gradient(135deg, #052E16, #166534, #052E16)", padding: "48px 24px", marginTop: 64 }}><div style={{ maxWidth: 820, margin: "0 auto" }}><div style={{ color: "#bbf7d0", fontSize: 13, marginBottom: 12 }}>Tax planning · General framework</div><h1 style={{ color: "#F1F5F9", fontSize: "clamp(28px, 4vw, 40px)", lineHeight: 1.15, margin: "0 0 12px" }}>Old vs new tax regime: compare using your own eligible details</h1><p style={{ color: "#dcfce7", margin: 0, lineHeight: 1.6 }}>Rates, deductions, rebates and election procedures depend on the relevant tax period and taxpayer. Avoid applying a fixed deduction threshold to everyone.</p></div></div>
    <main style={{ maxWidth: 820, margin: "0 auto", padding: "30px 22px 56px", color: "var(--text)", lineHeight: 1.7 }}>
      <Script id="ld-art" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(article) }} /><Script id="ld-faq" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faq) }} />
      <nav aria-label="Breadcrumb" style={{ fontSize: 13, color: "var(--text-muted)", marginBottom: 22 }}><Link href="/" style={{ color: "inherit" }}>Home</Link> / <Link href="/learn/tax" style={{ color: "inherit" }}>Tax</Link> / Old vs new regime</nav>
      <section><h2 style={{ color: COLOR }}>Compare the tax that actually applies</h2><p>Start by identifying your filing status, income sources and the year covered by your return. Income earned in periods governed by different legislation may use different names and provisions. Do not copy a slab chart or deduction limit from a different year.</p><p>Then calculate both available options using the same income details. Include salary or business income, eligible exemptions and deductions, rebates, surcharge, cess, special-rate income and any other relevant adjustments. Use the current official calculator and instructions for the relevant return. Tax software should be set to the correct assessment year or tax year.</p></section>
      <section><h2 style={{ color: COLOR }}>The 2026 transition: assessment year vs tax year</h2><p>For income earned from 1 April 2025 to 31 March 2026, the return is for Assessment Year (AY) 2026–27 and remains governed by the Income-tax Act, 1961. Income earned from 1 April 2026 to 31 March 2027 is Tax Year 2026–27 under the Income-tax Act, 2025. The new Act taking effect does not move FY 2025–26 income into the new tax-year system.</p><p>When using a calculator or filing portal, select the period that matches when the income was earned—not simply the calendar year in which you file. See the Income Tax Department’s <a href="https://www.incometaxindia.gov.in/documents/20117/43120/FAQs-on-Interplay-and-Transition.pdf/dda21cfd-28be-d931-ad5c-6459ecbd2ea7?download=true" target="_blank" rel="noopener noreferrer" style={{ color: COLOR }}>official transition FAQs</a> for the applicable period and exceptions.</p></section>
      <section><h2 style={{ color: COLOR }}>A practical comparison checklist</h2><ol><li>Collect salary statements, interest certificates, investment and insurance records, rent and home-loan documents, and capital-gain information as applicable.</li><li>Check which claims are allowed under each regime for that exact year; do not assume that a deduction available under one is available under the other.</li><li>Confirm rebate eligibility, special-rate income treatment and any conditions for your residential or taxpayer status.</li><li>Compare final tax payable—not just slab rates or the gross value of deductions.</li><li>Review the election method and deadline, especially if you have business or professional income.</li></ol></section>
      <section><h2 style={{ color: COLOR }}>Do not change spending just for a tax deduction</h2><p>A deduction reduces eligible taxable income under specified conditions; it does not make an expense free. Consider liquidity, risk, lock-in and suitability before making an investment or insurance purchase. Do not buy a product solely to reach a generic “old regime wins” threshold.</p><p>For complex income, disputed eligibility or a material difference, consult a qualified tax professional. Keep supporting documents and verify the final return before filing.</p></section>
      <section><h2 style={{ color: COLOR }}>Frequently asked questions</h2>{faq.mainEntity.map((item) => <details key={item.name} style={{ borderBottom: "1px solid var(--border)", padding: "14px 0" }}><summary style={{ cursor: "pointer", fontWeight: 650 }}>{item.name}</summary><p style={{ color: "var(--text-muted)" }}>{item.acceptedAnswer.text}</p></details>)}</section>
      <p style={{ marginTop: 24 }}><a href="https://www.incometax.gov.in/iec/foportal/help/new-tax-vs-old-tax-regime-faqs?mobile-app=1" target="_blank" rel="noopener noreferrer" style={{ color: COLOR }}>Income Tax Department: old vs new regime FAQs</a> · <Link href="/learn/tax" style={{ color: COLOR }}>Tax guides</Link></p>
      <p style={{ borderTop: "1px solid var(--border)", paddingTop: 16, fontSize: 13, color: "var(--text-muted)" }}>General information, not tax or legal advice. Tax rules change and individual eligibility varies. Verify current official instructions or consult a qualified tax professional before acting.</p>
    </main>
  </>;
}
